
PS1="\e[48;5;239m\e[38;5;252m\u@\h\e[0m\e[48;5;4m\e[38;5;16m\w\e[0m\e[48;5;220m\e[38;5;8m \$(__git_ps1 "%s") \e[0m "

source ~/.git-prompt
export PATH=$PATH":$HOME/.emstel/bin"

_server()
{
  local current=${COMP_WORDS[COMP_CWORD]}
  WORDS="$(server list)"
  COMPREPLY=( $(compgen -W "$WORDS" -- $current) )
}

complete -F _server server

